version: '3'

services:

  java:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"

  keycloak:
    image: quay.io/keycloak/keycloak:10.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"